### ISSUE TITLE
Segmentation violation for empty data source

### ISSUE THREAD

**Issue by janritter** [terraform-linters/tflint-plugin-sdk#115]
When defining a data source without any attribute, you receive a segmentation violation. Defining an empty data source is valid for "aws_caller_identity"

## Code for the tflint rule
```go
// Check checks whether ...
func (r *TerraformThisRule) Check(runner tflint.Runner) error {
	_, err := runner.Config()
	if err != nil {
		return err
	}
	return nil
}

```

## Example failing with segmentation fault

```hcl
resource "aws_s3_bucket" "this" {
  bucket = "my-tf-test-bucket"
  acl    = "private"
}

data "aws_caller_identity" "current" {}
```

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18641ee]

goroutine 67 [running]:
github.com/terraform-linters/tflint/plugin.(*Server).encodeResource(0xc0001a1f08, 0xc0007b3180, 0xc00015d7d0)
        /private/tmp/tflint-20210425-9678-xk5bqe/tflint-0.28.0/plugin/encode.go:143 +0x22e
github.com/terraform-linters/tflint/plugin.(*Server).encodeModule(0xc0001a1f08, 0xc0009447e0, 0xc00056a320, 0xc0007f2be0, 0x100f0bb)
        /private/tmp/tflint-20210425-9678-xk5bqe/tflint-0.28.0/plugin/encode.go:95 +0xe2e
github.com/terraform-linters/tflint/plugin.(*Server).encodeConfig(0xc0001a1f08, 0xc0005055f0, 0x28, 0x3c185b8, 0x30)
        /private/tmp/tflint-20210425-9678-xk5bqe/tflint-0.28.0/plugin/encode.go:21 +0x5b
github.com/terraform-linters/tflint/plugin.(*Server).Config(0xc0001a1f08, 0x3712128, 0xc000150300, 0x0, 0x0)
        /private/tmp/tflint-20210425-9678-xk5bqe/tflint-0.28.0/plugin/server.go:111 +0x3a
reflect.Value.call(0xc000132d20, 0xc0003bc380, 0x13, 0x27439e9, 0x4, 0xc0007f2f08, 0x3, 0x3, 0x26dd240, 0xc00010e500, ...)
        /usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000132d20, 0xc0003bc380, 0x13, 0xc00077bf08, 0x3, 0x3, 0x2a40360, 0x100000001, 0xc0007b5290)
        /usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:337 +0xb9
net/rpc.(*service).call(0xc00012f680, 0xc000131090, 0xc0006342c0, 0xc0006342d0, 0xc0001fe480, 0xc00056a040, 0x221c7e0, 0x3712128, 0x16, 0x221c820, ...)
        /usr/local/Cellar/go/1.16.3/libexec/src/net/rpc/server.go:377 +0x189
created by net/rpc.(*Server).ServeCodec
        /usr/local/Cellar/go/1.16.3/libexec/src/net/rpc/server.go:474 +0x44d
```

## Working example

```hcl
resource "aws_s3_bucket" "this" {
  bucket = "my-tf-test-bucket"
  acl    = "private"
}

data "aws_caller_identity" "current" {
  test = "test"
}
```

**Comment by wata727** [comment]
This is a bug on the TFLint side. Released v0.28.1 with the bugfix.
